export const DEFAULT_NAV_BUTTON_ID = {
  TO_ROOT: "TO_ROOT",
  TO_ABOUT: "TO_ABOUT",
  TO_CONTACT: "TO_CONTACT",
  TO_LEGAL: "TO_LEGAL",
  TO_MEDIA: "TO_MEDIA",
  TO_SERVICES: "TO_SERVICES",
} as const;

export const DEFAULT_NAV_BUTTON_URL = {
  [DEFAULT_NAV_BUTTON_ID.TO_ROOT]: "/",
  [DEFAULT_NAV_BUTTON_ID.TO_ABOUT]: "/about",
  [DEFAULT_NAV_BUTTON_ID.TO_CONTACT]: "/contact",
  [DEFAULT_NAV_BUTTON_ID.TO_LEGAL]: "/legal",
  [DEFAULT_NAV_BUTTON_ID.TO_MEDIA]: "/media",
  [DEFAULT_NAV_BUTTON_ID.TO_SERVICES]: "/services",
} as const;

// use the link IDs as it pertains to the Mobile Nav service mappings as of now, but potentially
// further move the links into a more agnostic '/enums' directory where they will use the interfaces
// provided by repositories and services combined.

export const DEFAULT_NAV_BUTTON_TEXT = {
  [DEFAULT_NAV_BUTTON_ID.TO_ROOT]: "Home",
  [DEFAULT_NAV_BUTTON_ID.TO_ABOUT]: "About",
  [DEFAULT_NAV_BUTTON_ID.TO_CONTACT]: "Contact",
  [DEFAULT_NAV_BUTTON_ID.TO_LEGAL]: "Legal",
  [DEFAULT_NAV_BUTTON_ID.TO_MEDIA]: "Media",
  [DEFAULT_NAV_BUTTON_ID.TO_SERVICES]: "Services",
} as const;

const DEFAULT_NAV_BUTTONS_ON_LEGAL = [
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_ROOT,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_ROOT],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_ROOT],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_ABOUT,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_ABOUT],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_ABOUT],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_SERVICES,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_SERVICES],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_SERVICES],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_CONTACT,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_CONTACT],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_CONTACT],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_MEDIA,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_MEDIA],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_MEDIA],
  },
];

const DEFAULT_NAV_BUTTONS_ON_MEDIA = [
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_ROOT,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_ROOT],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_ROOT],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_ABOUT,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_ABOUT],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_ABOUT],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_SERVICES,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_SERVICES],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_SERVICES],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_CONTACT,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_CONTACT],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_CONTACT],
  },
  {
    id: DEFAULT_NAV_BUTTON_ID.TO_LEGAL,
    buttonText: DEFAULT_NAV_BUTTON_TEXT[DEFAULT_NAV_BUTTON_ID.TO_LEGAL],
    url: DEFAULT_NAV_BUTTON_URL[DEFAULT_NAV_BUTTON_ID.TO_LEGAL],
  },
];

export { DEFAULT_NAV_BUTTONS_ON_LEGAL, DEFAULT_NAV_BUTTONS_ON_MEDIA };
