export enum MOBILE_NAV_LINK_SET_ID {
  ROOT = "ROOT",
  ABOUT = "ABOUT",
  CONTACT = "CONTACT",
  LEGAL = "LEGAL",
  MEDIA = "MEDIA",
  SERVICES = "SERVICES",
}

export enum MOBILE_NAV_LINK_ID {
  TO_ROOT = "TO_ROOT",
  TO_ABOUT = "TO_ABOUT",
  TO_CONTACT = "TO_CONTACT",
  TO_LEGAL = "TO_LEGAL",
  TO_MEDIA = "TO_MEDIA",
  TO_SERVICES = "TO_SERVICES",
}

export const LINK_ROUTES = {
  [MOBILE_NAV_LINK_ID.TO_ROOT]: "/",
  [MOBILE_NAV_LINK_ID.TO_ABOUT]: "/about",
  [MOBILE_NAV_LINK_ID.TO_CONTACT]: "/contact",
  [MOBILE_NAV_LINK_ID.TO_LEGAL]: "/legal",
  [MOBILE_NAV_LINK_ID.TO_MEDIA]: "/media",
  [MOBILE_NAV_LINK_ID.TO_SERVICES]: "/services",
};
