import { MobileNavButton } from "../../../components/util/mobile-nav/mobile-nav-menu/mobile-nav-buttons/MobileNavButton_Interface";

const MOBILE_NAV_BUTTON_ID = {
  TO_ROOT: "TO_ROOT",
  TO_ABOUT: "TO_ABOUT",
  TO_CONTACT: "TO_CONTACT",
  TO_LEGAL: "TO_LEGAL",
  TO_MEDIA: "TO_MEDIA",
  TO_SERVICES: "TO_SERVICES",
} as const;

const MOBILE_NAV_BUTTON_URL = {
  [MOBILE_NAV_BUTTON_ID.TO_ROOT]: "/",
  [MOBILE_NAV_BUTTON_ID.TO_ABOUT]: "/about",
  [MOBILE_NAV_BUTTON_ID.TO_CONTACT]: "/contact",
  [MOBILE_NAV_BUTTON_ID.TO_LEGAL]: "/legal",
  [MOBILE_NAV_BUTTON_ID.TO_MEDIA]: "/media",
  [MOBILE_NAV_BUTTON_ID.TO_SERVICES]: "/services",
} as const;

// use the link IDs as it pertains to the Mobile Nav service mappings as of now, but potentially
// further move the links into a more agnostic '/enums' directory where they will use the interfaces
// provided by repositories and services combined.

const MOBILE_NAV_BUTTON_TEXT = {
  [MOBILE_NAV_BUTTON_ID.TO_ROOT]: "Home",
  [MOBILE_NAV_BUTTON_ID.TO_ABOUT]: "About",
  [MOBILE_NAV_BUTTON_ID.TO_CONTACT]: "Contact",
  [MOBILE_NAV_BUTTON_ID.TO_LEGAL]: "Legal",
  [MOBILE_NAV_BUTTON_ID.TO_MEDIA]: "Media",
  [MOBILE_NAV_BUTTON_ID.TO_SERVICES]: "Services",
} as const;

const MOBILE_NAV_BUTTONS_ON_ROOT: MobileNavButton[] = [
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ABOUT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_SERVICES,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_CONTACT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_LEGAL,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_MEDIA,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
  },
] as const;

const MOBILE_NAV_BUTTONS_ON_ABOUT: MobileNavButton[] = [
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ROOT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ROOT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ROOT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_SERVICES,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_CONTACT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_LEGAL,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_MEDIA,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
  },
] as const;

const MOBILE_NAV_BUTTONS_ON_SERVICES: MobileNavButton[] = [
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ROOT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ROOT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ROOT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ABOUT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_CONTACT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_LEGAL,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_MEDIA,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
  },
] as const;

const MOBILE_NAV_BUTTONS_ON_MEDIA: MobileNavButton[] = [
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ROOT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ROOT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ROOT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ABOUT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_SERVICES,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_CONTACT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_CONTACT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_LEGAL,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
  },
] as const;

const MOBILE_NAV_BUTTONS_ON_CONTACT: MobileNavButton[] = [
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ROOT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ROOT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ROOT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_ABOUT,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_ABOUT],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_SERVICES,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_SERVICES],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_LEGAL,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_LEGAL],
  },
  {
    id: MOBILE_NAV_BUTTON_ID.TO_MEDIA,
    text: MOBILE_NAV_BUTTON_TEXT[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
    url: MOBILE_NAV_BUTTON_URL[MOBILE_NAV_BUTTON_ID.TO_MEDIA],
  },
] as const;

export {
  MOBILE_NAV_BUTTONS_ON_ROOT,
  MOBILE_NAV_BUTTONS_ON_ABOUT,
  MOBILE_NAV_BUTTONS_ON_CONTACT,
  MOBILE_NAV_BUTTONS_ON_MEDIA,
  MOBILE_NAV_BUTTONS_ON_SERVICES,
};
